#!/bin/bash

#set -euo pipefail

# Globbing pattern defaults to "*.md"
pattern=${BUILDKITE_PLUGIN_SPELL_CHECKER_PATTERN-*.md}

spell_errors=$(docker run --rm -v $PWD:/workdir tmaier/markdown-spellcheck:latest --report "$pattern")
spell_return=$?

if [ $spell_return -ne 0 ] ; then
  echo -e "$spell_errors" | buildkite-agent annotate --style "warning"
fi

echo -e "$spell_errors"

